before:
  hooks:
    # - go mod tidy
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    binary: warrant
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: warrant
    homepage: "https://warrant.dev"
    tap:
      owner: warrant-dev
      name: homebrew-warrant
    commit_author:
      name: Warrant
      email: hello@warrant.dev
